### PR TITLE
Add travis-ci

### PR DESCRIPTION
**Pull request by stuaxo**
Having a go at getting travis to run the doctests.

### CODE REVIEW

**Comment by jceb** [comment]
Thanks, I don't really have the time to dive deeper into it. Would you be interested in helping to maintain this project?

**Comment by jceb** [comment]
Thanks, I don't really have the time to dive deeper into it. Would you be interested in helping to maintain this project?

**Comment by stuaxo** [comment]
I'm happy to get commit access and make small changes, like the above.
Dex mostly works so probably doesn't need too much doing, which is handy as I don't have huge amounts of time either.

It could be worth making an organisation on github for Dex and adding us, then I can sort out CI for it.

**Comment by jceb** [comment]
Sorry, this took a while. I added you to the repository.

**Comment by stuaxo** [comment]
No problem, it can take me this amount of time to come back to projects.

**Comment by stuaxo** [comment]
Think I need to withdraw this PR and replace with one for github actions.

**Pull request closed without merging**
